### PR TITLE
Reorganize news page for usnistgov/OSCAL-Pages#21.

### LINKED ISSUE #21: OSCAL Website: Update News Site with Current OSCAL Related News
4th Issue Created from usnistgov/OSCAL#1733 

# User Story:
As a user, I would like to visit a webpage to view all latest OSCAL related news. The NEWS page should be accessible from the main page, and be marked appropriately when 'new' NEWS are posted. The existing page: https://pages.nist.gov/OSCAL/about/news/ should be sunset.

## Goals:
- [x] The NEWS page gains proper visibility
- [x] Old "NEWS" are archived in a separate (appropriate) page.
- [x]  The Website is modified to highlight the information and navigate with ease
- [x] A Pull Request is submitted containing the above changes.

## Dependencies:
- [x] Compile and prioritize any noteworthy OSCAL news to be added to the page.

## Acceptance Criteria
- [ ] The current page is moved to gain proper visibility
- [x] The page is updated to not preserve old information
- [x] Old "NEWS" should be archived in a separate (appropriate) page.
- [ ]  The Website is modified to highlight the information and navigate with ease
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

### PR DESCRIPTION
**Pull request by aj-stein-nist**
Closes #21.

### CODE REVIEW

**Comment by aj-stein-nist** [comment]
OK, we have a series of changes we need to make to reorganize the top menu, and I know many of them will be collapsed. That work is out of scope for this issue. In the anticipation of those changes and acknowledging that the top menu items are too numerous, I would concede that news is very important, so in the interim I would recommend we put it as the first entry, after About. We will do that with the expectation we remove others in the near future as scoped in other upcoming tasks in the backlog.

image

**Comment by wendellpiez** [comment]
This is aspirational, if not yet the best we can do:

- About
- News & events
- Reference
  - (model documentation)
  - specifications
- Learn
  - concepts
  - tutorials
- Resources
  - downloads
  - examples / test sets
   - tools
- Contribute
  - community forums, lists and points of contact
  - contact us

(Even six items may be too many....)

**Comment by aj-stein-nist** [comment]
> This is aspirational, if not yet the best we can do:
> ...
> (Even six items may be too many....)

I appreciate the recommendation, I just know we need to handle outside the PR related issue (which comes after this). I like the recommendation, I just don't want to address them in this PR for the issue as scoped. Thanks for the recommendation!

**Comment by iMichaela** [comment]
> This is aspirational, if not yet the best we can do:
> 
> * About
> * News & events
> * Reference
>   
>   * (model documentation)
>   * specifications
> * Learn
>   
>   * concepts
>   * tutorials
> * Resources
>   
>   * downloads
>   * examples / test sets
>   * tools
> * Contribute
>   
>   * community forums, lists and points of contact
>   * contact us
> 
> (Even six items may be too many....)

@wendellpiez - we have issues that are aggregating pages under fewer tabs. For example, @Arminta-Jenkins-NIST is working on aggregating Concepts, Reference, Downloads, Examples, Tools under a new Resources tab. She is using Miro board shared with the team earlier.

**Comment by iMichaela** [comment]
@aj-stein-nist  - Placing ```news``` in the  ```about``` director:    ```src/content/about/news/_index.md``` and  ````src/content/about/news/archive.md```  does not seem to be optimal.  Isn't better to move it one level up: ```src/content/news/_index.md``` and  ````src/content/news/archive.md```

Also, the _index.md file contains the archive and the archive.md file contains the news we discussed to keep: the major OSCAL releases.

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist - Placing `news` in the `about` directory: `src/content/about/news/_index.md` and `src/content/about/news/archive.md` does not seem to be optimal. Isn't better to move it one level up: `src/content/news/_index.md` and `src/content/news/archive.md`

That's where [it currently is](https://github.com/usnistgov/OSCAL-Pages/blob/bcb50d4689965a3b0e8fd5145089c5264a09dd8a/src/content/about/news.md), just changed from a single file from a directory. I don't disagree, but that the reorganization was specifically the issue that was not in scope for this issue in PR, it should be handled in #24.

> Also, the _index.md file contains the archive and the archive.md file contains the news we discussed to keep: the major OSCAL releases.

Actually, that is one funny gaff, I did switch them and didn't even notice until now. 🤦 I will fix that later today and ask for a final review.

**Comment by aj-stein-nist** [comment]
OK I redid the commit and inverted the context mix-up to be correct, as caught by Michaela. This is ready for review again. Re #28, I want to focus on just touching up the content and the larger reorganization will continue in usnistgov/OSCAL-Pages#28.

**Review by Compton-NIST — APPROVED** [review]

**Pull request merged**
